### ISSUE TITLE
L10n

### ISSUE THREAD

**Issue by rodrigopadula** [wikimedia-research/translation-recs-app#36]
I would like to contribute with interface localization to Brazilian Portuguese, to use and spread that tool here.
How can I help?

**Comment by leilaz** [comment]
Hi @rodrigopadula . We are very happy that you want to take this project to Portuguese. We are currently working to make the app available for translation in translatewiki.net. If you are on phabricator, you can follow the task at https://phabricator.wikimedia.org/T128879 . If you are not, I can update you here as soon as we are ready in translatewiki. Thanks again. :)

**Comment by leilaz** [comment]
@rodrigopadula we have set up the environment for translations. It would be great if you help with the translations to Portuguese in [translatewiki](https://translatewiki.net/w/i.php?title=Special:Translate&group=gapfinder&language=pt&filter=%21translated&action=translate)
