### ISSUE TITLE
Missing static files after bower install

### ISSUE THREAD

**Issue by sabyasachi** [wikimedia-research/translation-recs-app#42]
Hi,

I ran `bower install` from inside `api/static`. When I opened `http://localhost:5000`, I saw `404` for two static files. They are:

- http://localhost:5000/static/bower_components/uls/src/jquery.uls.regionfilter.js
- http://localhost:5000/static/bower_components/uls/css/jquery.uls.compact.css

**Comment by Nikerabbit** [comment]
Those come from jquery.uls. I guess someone updated it to latest version. Those files were removed recently from jquery.uls. One should check that ULS still works okay and looks okay given we removed compact mode and made it the default, in cause you used the compact mode or had custom stylings.

**Comment by schana** [comment]
The discussion that spawned from this task is being tracked here: https://phabricator.wikimedia.org/T135211
