### ISSUE TITLE
Beacon EventLogger Doesn't work due to CORS

### ISSUE THREAD

**Issue by sabyasachi** [wikimedia-research/translation-recs-app#45]
Steps to replicate the issue:

- Select source and target language
- Go. You'll see the following error:
`
XMLHttpRequest cannot load https://meta.wikimedia.org/beacon/event?%7B%22schema%22%3A%22TranslationRec…22%2C%22requestToken%22%3A%2299145869-bb31-4452-8c54-9f3a1157e0dd%22%7D%7D. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://recommend.wmflabs.org' is therefore not allowed access.`

We should fix it at http://recommend.wmflabs.org/. It'll be great if it could work on a development environment as well.

**Comment by schana** [comment]
Since we aren't using the result, the only thing we care about is that the request is made. However, it would probably be good if, when running the site in a development environment, it didn't send events to the beacon endpoint.

**Comment by schana** [comment]
> it would probably be good if, when running the site in a development environment, it didn't send events to the beacon endpoint

5e245b96205fbc0c1e9a1b750107211d840e806c
